const state={view:"home",channel:"我想买",tasks:[
  {id:1, title:"寻找天使投资人", from:"王小姐", depth:3, points:30000, status:"待处理", participants:12, location:"同城", deadline:"30天", role:"承接", desc:"需要对早期项目进行资金支持，期望有相关行业经验"},
  {id:2, title:"找到 Apple 采购资源", from:"好友B", depth:2, points:6500, status:"等待回复", participants:10, location:"线上", deadline:"14天", role:"引荐", desc:"希望获取企业级采购渠道与折扣信息"},
  {id:3, title:"采购稀缺红酒", from:"闺蜜D", depth:3, points:2500, status:"已成交", participants:7, location:"同城", deadline:"7天", role:"承接", desc:"寻找可靠渠道购入小批量红酒"},
  {id:4, title:"对接高校活动嘉宾", from:"活动组A", depth:2, points:3200, status:"待处理", participants:5, location:"同城", deadline:"10天", role:"引荐", desc:"寻找科技创业主题演讲嘉宾"},
  {id:5, title:"企业法务咨询", from:"HR小李", depth:4, points:5800, status:"等待回复", participants:8, location:"线上", deadline:"15天", role:"承接", desc:"劳动合同与合规咨询"},
  {id:6, title:"二手服务器采购", from:"IT老王", depth:2, points:12000, status:"待处理", participants:9, location:"同城", deadline:"20天", role:"引荐", desc:"采购 10 台测试用服务器"},
  {id:7, title:"品牌设计 Logo", from:"创业者K", depth:3, points:4000, status:"等待回复", participants:6, location:"线上", deadline:"12天", role:"承接", desc:"初创项目需要基础品牌设计"},
  {id:8, title:"招聘安卓工程师", from:"招聘方M", depth:2, points:9000, status:"待处理", participants:11, location:"同城", deadline:"25天", role:"引荐", desc:"3 年经验，能独立负责模块"},
  {id:9, title:"商务渠道合作", from:"渠道商Z", depth:5, points:15000, status:"已成交", participants:13, location:"线上", deadline:"已完成", role:"承接", desc:"寻找区域代理商资源"},
  {id:10, title:"短视频拍摄剪辑", from:"内容团队T", depth:2, points:2600, status:"待处理", participants:4, location:"同城", deadline:"5天", role:"承接", desc:"宣传片拍摄剪辑制作"},
  {id:11, title:"跨境支付方案", from:"外贸公司Y", depth:6, points:22000, status:"等待回复", participants:10, location:"线上", deadline:"18天", role:"引荐", desc:"接入合规跨境支付"},
  {id:12, title:"供应链仓储对接", from:"电商S", depth:4, points:13000, status:"待处理", participants:7, location:"同城", deadline:"9天", role:"承接", desc:"本地仓储与配送解决方案"}
]};
function qs(s){return document.querySelector(s)}
function qsa(s){return Array.from(document.querySelectorAll(s))}
function showView(id){qsa('.view').forEach(v=>v.classList.remove('active'));qs('#'+id).classList.add('active');state.view=id;qsa('.nav').forEach(n=>{n.classList.toggle('active',n.dataset.view===id)});if(id==="home")renderHome();if(id==="taskList")renderTaskList();if(id==="taskDetail")renderTaskDetail(state.tasks[0].id)}
function renderHome(){const wrap=qs('#homeList');wrap.innerHTML='';state.tasks.slice(0,3).forEach(t=>{const el=document.createElement('div');el.className='card';el.innerHTML=`<div class="left"><div class="title">求购——${t.title}</div><div class="row spread"><span>悬赏积分：${t.points}</span><span>参与引荐：${t.participants}人</span></div></div><div class="action"><button class="primary" data-id="${t.id}">去申请</button></div>`;wrap.appendChild(el)});wrap.querySelectorAll('button').forEach(b=>b.addEventListener('click',e=>{const id=+e.currentTarget.dataset.id;openDetail(id)}))}
function toCN(n){const map=['零','一','二','三','四','五','六'];return map[Math.min(Math.max(n,0),6)]}
function renderTaskList(){const wrap=qs('#taskCards');wrap.innerHTML='';state.tasks.forEach(t=>{const el=document.createElement('div');el.className='card card-task';const statusClass=t.status==='待处理'?'status-pending':(t.status==='等待回复'?'status-wait':'status-done');const depthCN=toCN(Math.min(t.depth||3,6));el.innerHTML=`<div class="left clickable" data-id="${t.id}"><div class="title">${t.title}</div><div class="desc">来自：${t.from}（${depthCN}度人脉）</div><div class="row spread"><span>悬赏 ${t.points} 积分</span><span></span></div></div><div class="status-pill ${statusClass}">${t.status}</div><div class="action actions pos-br">${t.status==='待处理'?`<button class="primary sm" data-act="solve" data-id="${t.id}">我就是TA</button><button class="blue sm" data-act="forward" data-id="${t.id}">转发</button><button class="red sm" data-act="reject" data-id="${t.id}">拒绝</button>`:t.status==='等待回复'?`<button class="gray sm" data-act="detail" data-id="${t.id}">查看详情</button>`:`<button class="muted sm" data-act="detail" data-id="${t.id}">查看详情</button>`}</div>`;wrap.appendChild(el)});
  wrap.querySelectorAll('.left.clickable').forEach(n=>n.addEventListener('click',e=>{const id=+e.currentTarget.dataset.id;openDetail(id)}));
  wrap.querySelectorAll('button[data-id]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();const id=+e.currentTarget.dataset.id;const act=e.currentTarget.dataset.act;if(act==='solve')openModal('我就是TA',id);if(act==='forward')openDetail(id);if(act==='reject')openDetail(id);if(act==='detail')openDetail(id)}))}
function renderTaskDetail(id){const t=state.tasks.find(x=>x.id===id)||state.tasks[0];const dw=qs('#detailWrap');const depthCN=toCN(Math.min(t.depth||3,6));dw.innerHTML=`<div class="title" style="font-size:16px;font-weight:600">${t.title}</div><div class="row"><span>状态 ${t.status}</span><span>悬赏 ${t.points} 积分</span><span>${t.location}</span><span>截止 ${t.deadline}</span></div><div class="row"><span>来自：${t.from}（${depthCN}度人脉）</span><span>引荐人数 ${t.participants} 人</span></div><div style="margin-top:8px;color:#666;font-size:13px">${t.desc}</div>`;const cw=qs('#chainWrap');cw.innerHTML='';['A 发布者','B 我','C 被引荐','D 解决者'].forEach((n,i)=>{const el=document.createElement('div');el.className='node';el.textContent=n;cw.appendChild(el)});const actions=qs('.detail-actions');actions.innerHTML='';if(t.status==='待处理'){actions.innerHTML=`<button class="primary" id="btnApplySolve">我就是TA</button><button class="blue" id="btnForward">转发</button><button class="red" id="btnReject">拒绝</button>`}else if(t.status==='等待回复'){actions.innerHTML=`<button class="gray" id="btnDetailOnly">查看详情</button>`}else{actions.innerHTML=`<button class="muted" id="btnDetailDone">查看详情</button>`}qs('#btnApplySolve')&& (qs('#btnApplySolve').onclick=()=>openModal('我就是TA',id));qs('#btnForward')&& (qs('#btnForward').onclick=()=>openDetail(id));qs('#btnReject')&& (qs('#btnReject').onclick=()=>openDetail(id))}
function openDetail(id){showView('taskDetail');renderTaskDetail(id)}
function openModal(type,id){qs('#modalTitle').textContent=type;qs('#modalBody').innerHTML=type==='我就是TA'?`<div style="display:flex;flex-direction:column;gap:8px"><input type="text" placeholder="说明：我可直接完成"><input type="text" placeholder="预计完成时间"></div>`:`<div style="display:flex;flex-direction:column;gap:8px"><input type="text" placeholder="线索姓名"><input type="text" placeholder="联系方式"><input type="text" placeholder="证明材料链接"><input type="text" placeholder="贡献说明"></div>`;qs('#modal').style.display='flex';qs('#modalSubmit').onclick=()=>{qs('#modal').style.display='none'};qs('#modalClose').onclick=()=>{qs('#modal').style.display='none'}}
qsa('.nav').forEach(n=>n.addEventListener('click',()=>showView(n.dataset.view)))
qsa('.tab').forEach(t=>t.addEventListener('click',e=>{qsa('.tab').forEach(x=>x.classList.remove('active'));e.currentTarget.classList.add('active');state.channel=e.currentTarget.dataset.channel;renderHome()}))
qs('#btnPublishShortcut') && (qs('#btnPublishShortcut').onclick=()=>showView('publish'))
qs('#btnAsset')&& (qs('#btnAsset').onclick=()=>showView('points'))
qs('#fabPublish').onclick=()=>showView('publish')
qs('#searchBtn').onclick=()=>{}
showView('home');initTicker()
qs('#btnCheckin')&& (qs('#btnCheckin').onclick=()=>{const el=qs('#pointsTotal');el.textContent=String(Number(el.textContent||0)+10)})
qs('#btnRecharge')&& (qs('#btnRecharge').onclick=()=>showView('points'))
qs('#btnVoucher')&& (qs('#btnVoucher').onclick=()=>showView('points'))
qsa('.quad-item').forEach(b=>b.addEventListener('click',()=>{const v=b.dataset.view;v&& showView(v)}))
function genTickerItems(n){const users=['张三','李四','王五','赵六','钱七','孙八','周九','吴十','小明','小红','小周','小林','阿杰','阿明','阿强','阿慧','小李','小王','小赵','麦克'];const connectors=['马大姐','王老师','陈总','林姐','李哥','王总','赵总','刘姐','吴老板','周经理'];const nums=[2,3,4,5,6];const vals=[2000,3000,5000,6000,8000,9000,12000,15000,20000];const arr=[];for(let i=0;i<n;i++){const u=users[Math.floor(Math.random()*users.length)];const c=connectors[Math.floor(Math.random()*connectors.length)];const k=nums[Math.floor(Math.random()*nums.length)];const v=vals[Math.floor(Math.random()*vals.length)];arr.push(`用户${u}通过${c}等${k}人连接价值¥${v}的资源`)}return arr}
const tickerItems=genTickerItems(120);
let tickerInit=false;function initTicker(){if(tickerInit)return;const list=qs('#tickerList');if(!list)return;list.innerHTML=tickerItems.map(t=>`<li class="ticker-item">${t}</li>`).join('');let i=0;setInterval(()=>{i=(i+1)%tickerItems.length;list.style.transform=`translateY(-${i*32}px)`},1200);tickerInit=true}